
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Dachdecker</title>
	<link rel="stylesheet" type="text/css" href="/static/extjs/resources/css/ext-all.css">
	<script src="/static/extjs/ext-all-debug.js" ></script>
	<script src="/static/extjs/app.js" ></script>
	
    </head>

    <body>
	
	
	<div id="content">
	    <?php echo $this->layout()->content?>
	</div>

	
    </body>
</html>